// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RVPark.Data;

#nullable disable

namespace RVPark.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260630004742_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("RVPark.Models.RvSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HookupType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRvLength")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NightlyRate")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteNumber")
                        .IsUnique();

                    b.ToTable("RvSites");
                });
#pragma warning restore 612, 618
        }
    }
}
